name: "release"

on:
  push:
    branches:
      - main

jobs:
  release-lol-lens:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: "windows-latest"

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: setup bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: install frontend dependencies
        run: bun install

      - name: build
        run: bun tauri build

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./src-tauri/target/release/lol-lens.exe
